"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar/Sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [collapsed, setCollapsed] = useState(true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar collapsed={collapsed} setCollapsed={setCollapsed} />
        <div className={`container ${collapsed ? "" : "collapsed"}`}>{children}</div>
      </body>
    </html>
  );
}

// className={inter.className}
